# Template for ibutsu prod server
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ibutsu-backend-template
# ===============================================
# Backend
# ===============================================
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: ibutsu-backend
  spec:
    replicas: 1
    selector:
      deploymentConfig: ibutsu-backend
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentConfig: ibutsu-backend
      spec:
        containers:
        - env:
          - name: GUNICORN_PROCESSES
            value: "1"
          - name: PORT
            value: "8080"
          - name: APP_CONFIG
            value: config.py
          - name: HAS_FRONTEND
            value: "false"
          - name: POSTGRESQL_HOST
            valueFrom:
              secretKeyRef:
                key: db.host
                name: ibutsu-db
          - name: POSTGRESQL_PORT
            valueFrom:
              secretKeyRef:
                key: db.port
                name: ibutsu-db
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: db.user
                name: ibutsu-db
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.password
                name: ibutsu-db
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: db.name
                name: ibutsu-db
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.password
                name: redis
                optional: true
          - name: REDIS_HOSTNAME
            valueFrom:
              secretKeyRef:
                key: db.endpoint
                name: redis
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                key: db.port
                name: redis
          - name: IBUTSU_SUPERADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                key: email
                name: ibutsu-superadmin
          - name: IBUTSU_SUPERADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: ibutsu-superadmin
          - name: IBUTSU_SUPERADMIN_NAME
            valueFrom:
              secretKeyRef:
                key: name
                name: ibutsu-superadmin
          - name: CELERY_BROKER_URL
            value: redis://:${REDIS_PASSWORD}@${REDIS_HOSTNAME}
          - name: CELERY_RESULT_BACKEND
            value: redis://:${REDIS_PASSWORD}@${REDIS_HOSTNAME}
          - name: FRONTEND_URL
            value: https://${FRONTEND_ROUTE}
          - name: BACKEND_URL
            value: https://${BACKEND_ROUTE}
          image: backend
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 20
          name: ibutsu-backend
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 20
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ibutsu-backend
        from:
          kind: ImageStreamTag
          name: backend:latest
      type: ImageChange
    - type: ConfigChange
# -----------------------------------------------
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: ibutsu-backend
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ibutsu-backend
# -----------------------------------------------
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: ibutsu-backend
    annotations:
      description: "A route to the backend"
  spec:
    host: ${BACKEND_ROUTE}
    to:
      kind: Service
      name: ibutsu-backend
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
# ------------------------------------------------
- kind: Secret
  apiVersion: v1
  metadata:
    name: ibutsu-superadmin
  type: opaque
  stringData:
    email: ${IBUTSU_SUPERADMIN_EMAIL}
    password: ${IBUTSU_SUPERADMIN_PASSWORD}
    name: ${IBUTSU_SUPERADMIN_NAME}
# ===============================================
# Parameters
# ===============================================
parameters:
- name: APP_NAME
  displayName: App Name
  description: The name of the application
  value: ibutsu-server
- name: BACKEND_ROUTE
  displayName: Backend Route
  description: The URL of the backend of the Ibutsu server
  value: ibutsu-api.example.com
- name: FRONTEND_ROUTE
  displayName: Frontend Route
  description: The URL of the frontend of the Ibutsu server
  value: ibutsu.example.com
- name: REDIS_PASSWORD
  displayName: Redis Password
  description: The password for Redis
  generate: expression
  from: '[\w]{16}'
- name: IBUTSU_SUPERADMIN_EMAIL
  displayName: Superadmin Email
  description: The email for the superadmin of Ibutsu
  generate: expression
  from: 'admin-[\a\d]{8}@ibutsu.com'
- name: IBUTSU_SUPERADMIN_PASSWORD
  displayName: Superadmin Password
  description: The password for the superadmin of Ibutsu
  generate: expression
  from: '[\w]{16}'
- name: IBUTSU_SUPERADMIN_NAME
  displayName: Superadmin Name
  description: The name superadmin of Ibutsu
  value: Ibutsu Admin
