# Template for ibutsu prod server
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ibutsu-flower-template
# ===============================================
# Flower
# ===============================================
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: celery-flower
  spec:
    replicas: 1
    selector:
      deploymentConfig: celery-flower
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentConfig: celery-flower
      spec:
        containers:
        - env:
          # TOOD: use redis secret to set this
          - name: BROKER_URL
            value: redis://:${REDIS_PASSWORD}@redis.${NAMESPACE}.svc
          image: celery-flower
          imagePullPolicy: IfNotPresent
          name: quay.io/ibutsu/celery-flower:${IMAGE_TAG}
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
# -----------------------------------------------
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: celery-flower
  spec:
    ports:
    - port: 8080
      targetPort: 5555
    selector:
      deploymentConfig: celery-flower
# ===============================================
# Parameters
# ===============================================
parameters:
- name: APP_NAME
  displayName: App Name
  description: The name of the application
  value: ibutsu-server
- name: BACKEND_ROUTE
  displayName: Backend Route
  description: The URL for flower in the Ibutsu server
  value: ibutsu-api.example.com
- name: IMAGE_TAG
  value: latest
