# Test Job for running a vacuum immediately
# The command should match that of 'pgsql-vacuum-cronjob' exactly
# To kickoff the job, run:
#   oc create -f pgsql-vacuum-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  creationTimestamp: null
  name: test-pgsql-vacuum
  namespace: iqe-ibutsu-server
spec:
  selector: {}
  template:
    metadata:
      name: test-psql-vacuum
    spec:
      containers:
        - name: postgresql-vacuum
          image: postgresql:12
          command:
            - 'bash'
            - '-eo'
            - 'pipefail'
            - '-c'
            - >
              trap "echo 'VACUUM failed'; exit 0" ERR;
              echo "Backing up database...";
              PGPASSWORD="$PGPASSWORD" psql --username=$PGUSER --host=$PGHOST --port=$PGPORT --dbname=$PGDATABASE --command 'VACUUM (verbose);';
              echo "";
              echo -n "VACUUM successful."
          resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
          env:
            - name: PGHOST
              value: postgresql.iqe-ibutsu-server.svc
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
      restartPolicy: Never
